SimpleOps/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import accounts.urls
from . import views
import accounts.user
import cmdb.urls
import chat.urls
import setup_jobs.urls
import deploy.urls
import api.urls
import delivery.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^login/',accounts.user.login,name='login'),
    url(r'^user/', include('accounts.urls')),
    url(r'^logout/', accounts.user.logout, name='logout'),
    url(r'^cmdb/',include('cmdb.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^setup_jobs/',include('setup_jobs.urls')),
    url(r'^deploy/',include('deploy.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^mfile/', include('mfile.urls')),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^delivery/', include('delivery.urls')),
    url(r'^config/$', views.config,name='config'),
    # url(r'^websocket/(?P<userid>[0-9]+)$',views.websocket_tst,name='websocket'),
]
handler400 = "SimpleOps.views.bad_request"
handler404 = "SimpleOps.views.page_not_found"
handler403 = "SimpleOps.views.page_not_permission"
handler500 = "SimpleOps.views.internl_error"

api/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    url(r'^assets/$', views.assets_list),
    url(r'^project/$', views.project_list),
    url(r'^project/(?P<id>[0-9]+)/$', views.project_detail),
    url(r'^inventory/(?P<id>[0-9]+)/$', views.inventory_detail),
    url(r'^service/$', views.service_list),
    url(r'^service/(?P<id>[0-9]+)/$', views.service_detail),
    url(r'^assets/(?P<id>[0-9]+)/$', views.assets_detail),

]

urlpatterns = format_suffix_patterns(urlpatterns)

cmdb/urls.py
from django.conf.urls import url

import views

app_name = "cmdb"
urlpatterns = [
    url(r'^report/', views.report, name='report'),
    url(r'^assets_info/$', views.assets_info, name='assets_info'),
    url(r'^project/', views.project, name='project'),
    url(r'^new_asset_permission/$', views.new_asset_permission, name='new_asset_permission'),
    url(r'^new_asset_del/(?P<asset_id>[0-9]+)/$', views.new_asset_del, name='new_asset_del'),
    url(r'^new_asset_allow/(?P<asset_id>[0-9]+)/$', views.new_asset_allow, name='new_asset_allow'),
    url(r'^business_unit/$', views.business_unit, name='business_unit'),
    url(r'^business_add/$', views.business_add, name='business_add'),
    url(r'^business_edit/(?P<bus_id>[0-9]+)/$', views.business_edit, name='business_edit'),
    url(r'^business_del/(?P<bus_id>[0-9]+)/$', views.business_del, name='business_del'),
    url(r'^project_list/$', views.project_list, name='project_list'),
    url(r'^project_add/$', views.project_add, name='project_add'),
    url(r'^project_edit/(?P<bus_id>[0-9]+)/$', views.project_edit, name='project_edit'),
    url(r'^project_del/(?P<bus_id>[0-9]+)/$', views.project_del, name='project_del'),
    url(r'^detail/(?P<asset_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^asset_server_query/$', views.assets_server_query, name='assets_server_query'),
    url(r'^asset_edit/(?P<asset_id>[0-9]+)/$', views.asset_edit, name='asset_edit'),
    url(r'^asset_del/(?P<asset_id>[0-9]+)/$', views.asset_del, name='asset_del'),
    url(r'^asset_add/', views.asset_add, name='asset_add'),
    url(r'^asset_batch_import/', views.asset_batch_import, name='asset_batch_import'),
]

delivery/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^list/', views.delivery_list, name='delivery_list'),
    url(r'^add/$', views.delivery_add, name='delivery_add'),
    url(r'^edit/(?P<pid>[0-9]+)/$', views.delivery_edit, name='delivery_edit'),
    url(r'^run/(?P<pid>[0-9]+)/$', views.delivery_run, name='delivery_run'),
    url(r'^init/(?P<pid>[0-9]+)/$', views.delivery_init, name='delivery_init'),
    url(r'^result/(?P<pid>[0-9]+)/$', views.delivery_result, name='delivery_result'),
    url(r'^version/(?P<pid>[0-9]+)/$', views.delivery_version, name='delivery_version'),
    url(r'^del/(?P<id>[0-9]+)/$', views.delivery_del, name='delivery_del'),
    url(r'^log/$', views.delivery_log, name='delivery_log'),

]

mfile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from mfile.views import finder,file_down,file_log,file_up,file_find
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^up/', file_up),
    url(r'^down/', file_down),
    url(r'^find/', file_find),
    url(r'^log/', file_log),
    url(r'^$',finder.as_view(),name='mfile'),
    url(r'^elfinder/',include('elfinder.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
    ]

delivery/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from cmdb.models import BusinessUnit
# Create your models here.
class Project_Config(models.Model):
    project_repertory_choices = (
        ('git', u'git'),
        ('svn', u'svn'),
    )
    deploy_model_choices = (
        ('branch', u'branch'),
        ('tag', u'tag'),
    )
    project = models.ForeignKey(BusinessUnit, related_name='project_config', on_delete=models.CASCADE,verbose_name='所属业务线')
    project_service = models.SmallIntegerField(verbose_name='所属业务')
    project_env = models.CharField(max_length=50, verbose_name='项目环境', default=None)
    project_name = models.CharField(max_length=100, verbose_name='项目名称', default=None)

    project_type = models.CharField(max_length=10, verbose_name='编译类型')
    project_local_command = models.TextField(blank=True, null=True, verbose_name='部署服务器要执行的命令', default=None)
    project_repo_dir = models.CharField(max_length=100, verbose_name='本地仓库目录', default=None)
    project_dir = models.CharField(max_length=100, verbose_name='代码目录', default=None)
    project_exclude = models.TextField(blank=True, null=True, verbose_name='排除文件', default=None)
    project_address = models.CharField(max_length=100, verbose_name='版本仓库地址', default=None)
    project_uuid = models.CharField(max_length=50, verbose_name='唯一id')
    project_repo_user = models.CharField(max_length=50, verbose_name='仓库用户名', blank=True, null=True)
    project_repo_passwd = models.CharField(max_length=50, verbose_name='仓库密码', blank=True, null=True)
    project_repertory = models.CharField(choices=project_repertory_choices, max_length=10, verbose_name='仓库类型',
                                         default=None)
    project_status = models.SmallIntegerField(verbose_name='是否激活', blank=True, null=True, default=None)
    project_remote_command = models.TextField(blank=True, null=True, verbose_name='部署之后执行的命令', default=None)
    project_user = models.CharField(max_length=50, verbose_name='项目文件宿主', default=None)
    project_model = models.CharField(choices=deploy_model_choices, max_length=10, verbose_name='上线类型', default=None)
    project_audit_group = models.SmallIntegerField(verbose_name='项目授权组', blank=True, null=True, default=None)

    def __unicode__(self):
        return self.project_name
    class Meta:

        unique_together = (("project_env", "project", "project_name"))
        verbose_name = '项目管理表'
        verbose_name_plural = '项目管理表'


class Log_Project_Config(models.Model):
    project_id = models.IntegerField(verbose_name='项目id', blank=True, null=True, default=None)
    project_user = models.CharField(max_length=50, verbose_name='操作用户', default=None)
    project_name = models.CharField(max_length=100, verbose_name='名称', default=None)
    project_content = models.CharField(max_length=100, default=None)
    project_branch = models.CharField(max_length=100, default=None, blank=True, null=True)
    create_time = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='执行时间')

    def __unicode__(self):
        return self.project_name
    class Meta:

        verbose_name = '项目配置操作记录表'
        verbose_name_plural = '项目配置操作记录表'


class Project_Number(models.Model):
    project = models.ForeignKey('Project_Config', related_name='project_number', on_delete=models.CASCADE)
    server = models.CharField(max_length=100, verbose_name='服务器IP', default=None)
    dir = models.CharField(max_length=100, verbose_name='项目目录', default=None)

    class Meta:
        unique_together = (("project", "server"))
        verbose_name = '项目成员表'
        verbose_name_plural = '项目成员表'

    def __unicode__(self):
        return '%s,%s' % (self.server, self.dir)

delivery/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

from .models import *





class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project_Config
        exclude = ('id','project_uuid')
        # fields = '__all__'
        widgets = {
            'project': forms.Select(attrs={'class': 'form-control'}),
            'project_env': forms.Select(choices=(('sit', u'测试'), ('uat', u'预生产'),
                                                 ('prod', u'生产')),
                                        attrs={'class': 'form-control'}),
            'project_name': forms.TextInput(attrs={'class': 'form-control'}),
            # 'project_service': forms.TextInput(attrs={'class': 'form-control'}),
            'project_service': forms.Select(attrs={'class': 'form-control'}),
            'project_type': forms.TextInput(attrs={'class': 'form-control'}),
            'project_local_command': forms.TextInput(attrs={'class': 'form-control'}),
            'project_repo_dir': forms.TextInput(attrs={'class': 'form-control'}),
            'project_dir': forms.TextInput(attrs={'class': 'form-control'}),
            'project_exclude': forms.TextInput(attrs={'class': 'form-control'}),
            'project_address': forms.TextInput(attrs={'class': 'form-control'}),
            'project_repo_user': forms.TextInput(attrs={'class': 'form-control'}),
            'project_repo_passwd': forms.TextInput(attrs={'class': 'form-control'}),
            'project_repertory': forms.Select(attrs={'class': 'form-control'}),
            'project_status': forms.Select(choices=((0, u'未激活'), (1, u'激活'),),
                                           attrs={'class': 'form-control'}),
            'project_remote_command': forms.TextInput(attrs={'class': 'form-control'}),
            'project_user': forms.TextInput(attrs={'class': 'form-control'}),
            'project_model': forms.Select(attrs={'class': 'form-control'}),
            'project_audit_group': forms.TextInput(attrs={'class': 'form-control','placeholder': '数值，如1'}),


        }

templates/delivery/delivery_add.html
{% extends 'base.html' %}


{% block title %}
    <title> ALANCMD-增加交付项目 </title>
{% endblock %}


{% block css-js %}
<link href="/static/css/bootstrap-multiselect.css" rel="stylesheet">
<script src="/static/js/bootstrap-multiselect.js"></script>

{% endblock %}


{% block page-title %}
    <h1 class="page-header text-overflow">Project Add</h1>
{% endblock %}

{% block content %}
 {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
 <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
					<li><a href="/">首页</a></li>
					<li><a href="/delivery/list/">项目交付列表</a></li>
					<li class="active">新增项目交付</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">新增项目交付</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-2">
                        </div>

                        <form class="form-horizontal" role="form" action={% url "delivery_add" %} method="POST">
                            {% csrf_token %}
                            <div class="col-lg-8">
                                <fieldset>
                                    {{ form }}

                                </fieldset>
                            <div class="form-group">
								<label> 目标服务器: </label> <br>
								<select multiple class="form-control" name="server" id="server"  required>
{#<!-- 									{% for ds in serverList %}#}
{#										<option name="server" value="{{ds.id}}">{{ds.ip}}</option> #}
{#									{% endfor %} -->#}
								</select>
							</div>
                            <br>
                                <div class="form-group" style="margin-left: 10px;">
{#                                    <div class="box-footer" style="margin-left: 10px;width: 530px;">#}
                                        <button type="submit" class="pull-left btn btn-primary">
                                            提交
                                        </button>&nbsp;
                                        <a class="pull-right btn btn-danger" href="{% url "cmdb:assets_info" %}">返回</a>
{#                                    </div>#}
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->


<script>
$(document).ready(function(){
    $('#id_project_service').attr("disabled",true);
    $('#server').attr("disabled",true);
    $('#id_project').change(oBtProjectSelect); //函数后面不加小括号，否则会自动执行
    $('#id_project_service').change({"model":"service"},oBtServiceSelect); //函数后面不加小括号，否则会自动执行,加入传入数据时以字典方式传入，取出是为event.data.model
    {#$('#id_project_service').bind('change','service',oBtServiceSelect); //函数后面不加小括号，否则会自动执行#}

});

function oBtProjectSelect(){

	   $('#id_project_service').removeAttr("disabled");
	   var obj = document.getElementById("id_project");
	   var index = obj.selectedIndex;
	   var projectId = obj.options[index].value;
	   if ( projectId > 0){
			$.ajax({
				dataType: "JSON",
				url:'/api/project/'+ projectId + '/', //请求地址
				type:"GET",  //提交类似
				success:function(response){
					var binlogHtml = '<select class="form-control" name="project_service" id="id_project_service" onchange="oBtServiceSelect("service");" required><option selected="selected"  value="">请选择业务类型</option>'
					var selectHtml = '';
					for (var i=0; i <response["service_assets"].length; i++){
						 selectHtml += '<option  value="'+ response["service_assets"][i]["id"] +'">' + response["service_assets"][i]["service_name"] + '</option>'
					};
					binlogHtml =  binlogHtml + selectHtml + '</select>';
					document.getElementById("id_project_service").innerHTML= binlogHtml;

				},
			});
	   }
	   else{
		   $('#id_project_service').attr("disabled",true);
	   }

}

function oBtServiceSelect(event){
 	   $('#server').removeAttr("disabled");
	   var obj = document.getElementById("id_project_service");
	   var index = obj.selectedIndex;
	   var sId = obj.options[index].value;
	   {#alert(sId)#}
	   if ( sId  > 0){
			$.ajax({
				dataType: "JSON",
				url:'/cmdb/asset_server_query/', //请求地址
				type:"POST",  //提交类似
				data:{
					{#"query":"service",#}
					"query":event.data.model,
					"id":sId
				},
				success:function(response){
					var binlogHtml = '<select multiple  name="server" id="server"  required>'
					var selectHtml = '';
					for (var i=0; i < response["data"].length; i++){
						 selectHtml += '<option name="server" value="'+ response["data"][i]["id"] +'">' + response["data"][i]["ip"] + ' | ' + response["data"][i]["project"] + ' | ' + response["data"][i]["service"] + '</option>';
						 {#console.log(i)#}
					};
					binlogHtml =  binlogHtml + selectHtml + '</select>';
                    {#alert(binlogHtml)#}
					document.getElementById("server").innerHTML= binlogHtml;
					$('#server').multiselect('destroy');
 				    $('#server').multiselect({
				        enableClickableOptGroups: true,
				        enableCollapsibleOptGroups: true,
				        includeSelectAllOption: true,
				       	enableFiltering: true,
				    });
				},
			});
	   }
	   else{
		   $('#server option:selected').empty();
		   $('#server').attr("disabled",true);
	   }

}

</script>
{% endblock %}

templates/delivery/delivery_edit.html
{% extends 'base.html' %}


{% block title %}
    <title> ALANCMD-修改交付项目 </title>
{% endblock %}


{% block css-js %}
<link href="/static/css/bootstrap-multiselect.css" rel="stylesheet">
<script src="/static/js/bootstrap-multiselect.js"></script>

{% endblock %}


{% block page-title %}
    <h1 class="page-header text-overflow">Project Edit</h1>
{% endblock %}

{% block content %}
 {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
 <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
					<li><a href="/">首页</a></li>
					<li><a href="/delivery/list/">项目交付列表</a></li>
					<li class="active">修改项目交付</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">新增项目交付</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-2">
                        </div>

                        <form class="form-horizontal" role="form" action={% url "delivery_edit" pid %} method="POST">
                            {% csrf_token %}
                            <div class="col-lg-8">
                                <fieldset>
                                    {{ form }}

                                </fieldset>
                            <div class="form-group">
								<label> 目标服务器: </label> <br>
								<select multiple class="form-control" name="server" id="server"  required>
{#<!-- 									{% for ds in serverList %}#}
{#										<option name="server" value="{{ds.id}}">{{ds.ip}}</option> #}
{#									{% endfor %} -->#}
								</select>
							</div>
                            <br>
                                <div class="form-group" style="margin-left: 10px;">
{#                                    <div class="box-footer" style="margin-left: 10px;width: 530px;">#}
                                        <button type="submit" class="pull-left btn btn-primary">
                                            提交
                                        </button>&nbsp;
                                        <a class="pull-right btn btn-danger" href="{% url "cmdb:assets_info" %}">返回</a>
{#                                    </div>#}
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->


<script>
$(document).ready(function(){
    $('#id_project_service').attr("disabled",true);
    $('#server').attr("disabled",true);
    $('#id_project').change(oBtProjectSelect); //函数后面不加小括号，否则会自动执行
    $('#id_project_service').change({"model":"service"},oBtServiceSelect); //函数后面不加小括号，否则会自动执行,加入传入数据时以字典方式传入，取出是为event.data.model
    {#$('#id_project_service').bind('change','service',oBtServiceSelect); //函数后面不加小括号，否则会自动执行#}

});

function oBtProjectSelect(){

	   $('#id_project_service').removeAttr("disabled");
	   var obj = document.getElementById("id_project");
	   var index = obj.selectedIndex;
	   var projectId = obj.options[index].value;
	   if ( projectId > 0){
			$.ajax({
				dataType: "JSON",
				url:'/api/project/'+ projectId + '/', //请求地址
				type:"GET",  //提交类似
				success:function(response){
					var binlogHtml = '<select class="form-control" name="project_service" id="id_project_service" onchange="oBtServiceSelect("service");" required><option selected="selected"  value="">请选择业务类型</option>'
					var selectHtml = '';
					for (var i=0; i <response["service_assets"].length; i++){
						 selectHtml += '<option  value="'+ response["service_assets"][i]["id"] +'">' + response["service_assets"][i]["service_name"] + '</option>'
					};
					binlogHtml =  binlogHtml + selectHtml + '</select>';
					document.getElementById("id_project_service").innerHTML= binlogHtml;

				},
			});
	   }
	   else{
		   $('#id_project_service').attr("disabled",true);
	   }

}

function oBtServiceSelect(event){
 	   $('#server').removeAttr("disabled");
	   var obj = document.getElementById("id_project_service");
	   var index = obj.selectedIndex;
	   var sId = obj.options[index].value;
	   {#alert(sId)#}
	   if ( sId  > 0){
			$.ajax({
				dataType: "JSON",
				url:'/cmdb/asset_server_query/', //请求地址
				type:"POST",  //提交类似
				data:{
					{#"query":"service",#}
					"query":event.data.model,
					"id":sId
				},
				success:function(response){
					var binlogHtml = '<select multiple  name="server" id="server"  required>'
					var selectHtml = '';
					for (var i=0; i < response["data"].length; i++){
						 selectHtml += '<option name="server" value="'+ response["data"][i]["id"] +'">' + response["data"][i]["ip"] + ' | ' + response["data"][i]["project"] + ' | ' + response["data"][i]["service"] + '</option>';
						 {#console.log(i)#}
					};
					binlogHtml =  binlogHtml + selectHtml + '</select>';
                    {#alert(binlogHtml)#}
					document.getElementById("server").innerHTML= binlogHtml;
					$('#server').multiselect('destroy');
 				    $('#server').multiselect({
				        enableClickableOptGroups: true,
				        enableCollapsibleOptGroups: true,
				        includeSelectAllOption: true,
				       	enableFiltering: true,
				    });
				},
			});
	   }
	   else{
		   $('#server option:selected').empty();
		   $('#server').attr("disabled",true);
	   }

}

</script>
{% endblock %}

templates/delivery/delivery_log.html
{% extends 'base.html' %}


{% block title %}
<title> 项目交付执行日志 </title>
{% endblock %}


{% block css-js %}

  <!--DataTables [ OPTIONAL ]-->
    <link href="/static/css/datatables.bootstrap.css" rel="stylesheet">
	<link href="/static/css/datatables.responsive.css" rel="stylesheet">
        <!--FooTable [ OPTIONAL ]-->
    <link href="/static/css/footable.core.css" rel="stylesheet">

   <script src="/static/js/jquery.datatables.js"></script>
    <script src="/static/js/datatables.bootstrap.js"></script>
	<script src="/static/js/datatables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="/static/js/tables-datatables.js"></script>
    <!--FooTable [ OPTIONAL ]-->
    <script src="/static/js/footable.all.min.js"></script>


    <!--FooTable Example [ SAMPLE ]-->
    <script src="/static/js/tables-footable.js"></script>


{% endblock %}


{% block page-title %}
<h1 class="page-header text-overflow">Project Delivery</h1>
{% endblock %}

{% block content %}
  <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
					<li><a href="/">首页</a></li>

					<li class="active">项目交付日志</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->

<div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">Project LOG</h3>
                        </div>


<br>
<br>
                            <!-- Foo Table - Pagination -->
                    <!--===================================================-->
                    <div class="panel-body">
					                <label class="form-inline">Show
					                    <select id="demo-show-entries" class="form-control input-sm">
					                        <option value="5">5</option>
					                        <option value="10">10</option>
					                        <option value="15">15</option>
					                        <option value="20">20</option>
					                    </select>
					                    entries
					                </label>
					                <table id="demo-foo-pagination" class="table toggle-arrow-tiny" data-page-size="5">
					                    <thead>
					                        <tr>
					                            <th data-toggle="true">序号</th>
					                            <th>项目环境</th>
					                            <th>所属业务线</th>
					                            <th>项目名称</th>
                                                <th>项目版本</th>
					                            <th>操作用户</th>
                                                <th>操作时间</th>
                                                <th data-hide="all">内容</th>
					                        </tr>
					                    </thead>
					                    <tbody>
                                        {% for data in data_list %}
                                        <tr>
                                          <td>{{ forloop.counter }}</td>
                                        <td>
                                        {% if data.project.project_env == 'sit' %}
                                            <span class="label label-success">测试环境</span>
                                        {% elif data.project.project_env == 'qa' %}
                                            <span class="label label-warning">预生产环境</span>
                                        {% elif data.project.project_env == 'uat' %}
                                            <span class="label label-danger">生产环境</span>
                                        {% endif %}
                                        </td>
					                            <td>{{ data.project.project}}</td>
					                            <td>{{ data.project_name }}</td>
					                            <td>{{ data.project_branch }}</td>
					                            <td>{{ data.project_user }}</td>
                                            <td>{{ data.create_time}}</td>
                                            <td>{{ data.project_content }}</td>

					                        </tr>
                                        {% empty %}
                                         <tr>没有数据！</tr>
                                        {% endfor %}

					                    </tbody>
					                    <tfoot>
					                        <tr>
					                            <td colspan="5">
					                                <div class="text-right">
					                                    <ul class="pagination"></ul>
					                                </div>
					                            </td>
					                        </tr>
					                    </tfoot>
					                </table>
					            </div>
                    <!--===================================================-->
                    <!-- End Foo Table - Pagination -->
					</div>


{% endblock %}