SimpleOps/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import accounts.urls
from . import views
import accounts.user
import cmdb.urls
import chat.urls
import setup_jobs.urls
import deploy.urls
import api.urls
import delivery.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^login/',accounts.user.login,name='login'),
    url(r'^user/', include('accounts.urls')),
    url(r'^logout/', accounts.user.logout, name='logout'),
    url(r'^cmdb/',include('cmdb.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^setup_jobs/',include('setup_jobs.urls')),
    url(r'^deploy/',include('deploy.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^mfile/', include('mfile.urls')),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^delivery/', include('delivery.urls')),
    url(r'^config/$', views.config,name='config'),
    # url(r'^websocket/(?P<userid>[0-9]+)$',views.websocket_tst,name='websocket'),
]
handler400 = "SimpleOps.views.bad_request"
handler404 = "SimpleOps.views.page_not_found"
handler403 = "SimpleOps.views.page_not_permission"
handler500 = "SimpleOps.views.internl_error"

api/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    url(r'^assets/$', views.assets_list),
    url(r'^project/$', views.project_list),
    url(r'^project/(?P<id>[0-9]+)/$', views.project_detail),
    url(r'^inventory/(?P<id>[0-9]+)/$', views.inventory_detail),
    url(r'^service/$', views.service_list),
    url(r'^service/(?P<id>[0-9]+)/$', views.service_detail),
    url(r'^assets/(?P<id>[0-9]+)/$', views.assets_detail),

]

urlpatterns = format_suffix_patterns(urlpatterns)

mfile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from mfile.views import finder,file_down,file_log,file_up,file_find
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^up/', file_up),
    url(r'^down/', file_down),
    url(r'^find/', file_find),
    url(r'^log/', file_log),
    url(r'^$',finder.as_view(),name='mfile'),
    url(r'^elfinder/',include('elfinder.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
    ]

mfile/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

class LogFileOps(models.Model):
    opstype = models.CharField(max_length=20,choices=(('up','分发'),('down','下载')),
                               verbose_name="操作类型",default='up')
    srcfile = models.CharField(max_length=100,verbose_name="源文件路径",blank=True,null=True,default=None)
    filepath = models.CharField(max_length=100,verbose_name="目标文件路径",blank=True,null=True,default=None)
    server = models.CharField(max_length=100,verbose_name="目标服务器")
    content = models.CharField(max_length=100,blank=True,null=True,verbose_name="备注")
    user = models.CharField(max_length=50, verbose_name='执行者', blank=True,null=True,default=None)
    create_time = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='执行时间')

    def __unicode__(self):
        return "{}:{}".format(self.opstype,self.create_time)

    class Meta:
        verbose_name = "文件操作记录表"

mfile/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from deploy.models import Ansible_Inventory

class FileUpForm(forms.Form):
    # inventory = forms.ChoiceField(choices=(('0','请选择资产类型'),('1','产品线'),('2','组别'),('3','动态资产表'),('4','自定义')),
    #                               required=True,label='资产类型',
    #                                widget=forms.Select(attrs={'class': 'form-control'}))

    inventory = forms.ModelChoiceField(queryset=Ansible_Inventory.objects.all(),
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    filepath = forms.CharField(required=True, label='目标路径',
                           error_messages={'required': u'请输入目标路径', 'invalid': u'格式错误'},
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': '/usr/local/src/',
                                                         }), )
    owner = forms.CharField(required=False, label='文件属主',
                           initial='root',
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'root',
                                                         }), )

    permission = forms.IntegerField(required=False, label='文件权限',
                           initial=755,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 755,
                                                         }), )
    content = forms.CharField(required=False, label='备注',
                           # initial='root',
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': '如：nginx配置修改',
                                                         }), )

class FileDownForm(forms.Form):
    # inventory = forms.ChoiceField(choices=(('1','产品线'),('2','组别'),('3','动态资产表'),('4','自定义')),
    #                               required=True,label='资产类型',
    #                                widget=forms.Select(attrs={'class': 'form-control'}))
    inventory = forms.ModelChoiceField(queryset=Ansible_Inventory.objects.all(),
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    filepath = forms.CharField(required=True, label='目标路径',
                           error_messages={'required': u'请输入目标路径', 'invalid': u'格式错误'},
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': '/usr/local/src/',
                                                         }), )
    content = forms.CharField(required=False, label='备注',
                              # initial='root',
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': '如：nginx配置修改',
                                                            }), )

mfile/views.py
# -*- coding: utf-8 -*-
import os,json
import uuid

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse,StreamingHttpResponse,FileResponse
from django.shortcuts import render_to_response, render
from django.utils.decorators import method_decorator
from django.views.generic.base import View

from accounts.permission import permission_verify
from deploy.ansible_api_v2 import ANSRunner
from deploy.log_ansible import AnsibleRecord
from deploy.redis_ops import Redis_pool
from deploy.views import get_json_inentory
from .forms import *
from .models import LogFileOps


class finder(LoginRequiredMixin, View):
    @method_decorator(permission_verify())
    def get(self, request):
        temp_name = "mfile/mfile-header.html"
        return render_to_response('mfile/finder.html', locals())


@login_required()
@permission_verify()
def file_up(request):
    if request.method == "GET":
        form = FileUpForm()
        uuidkey = uuid.uuid4()
        return render(request, "mfile/file_up.html", locals())
    elif request.method == "POST":
        scripts_uuid = request.POST.get('uuidkey')
        form = FileUpForm(request.POST)

        if form.is_valid():
            descpath = form.cleaned_data['filepath']
            permission = form.cleaned_data['permission']
            owner = form.cleaned_data['owner']
            inventory = form.cleaned_data['inventory']
            content = form.cleaned_data['content']
            # print model,args,debug,inventory
            resource, sList = get_json_inentory(inventory.id, pw="get")

            fileobj = request.FILES.get("file_upload", None)
            # fileName = None
            filePath = None
            if fileobj:
                # fileName = os.path.join('/upload/myfile/upload', fileobj.name)
                filePath = os.path.join(os.getcwd(), 'upload/myfile/upload',fileobj.name)
                # if os.path.isdir(os.path.dirname(filename)) is not True:
                if not os.path.exists(os.path.join(os.getcwd(), 'upload/myfile/upload')):
                    # print("dir not exists,make it")
                    os.makedirs(os.path.join(os.getcwd(), 'upload/myfile/upload'))
                try:
                    with open(filePath, 'wb') as f:
                        for chunk in fileobj.chunks():
                            f.write(chunk)
                except Exception as e:
                    print e

                scripts_args = "src={} dest={} owner={} mode={} backup=yes".format(filePath,
                                                                                  descpath,
                                                                                   owner,permission )
                redisKey = scripts_uuid
                # logId = AnsibleRecord.Model.insert(user=str(request.user), ans_model='copy',
                #                                    ans_server=','.join(sList), ans_args=filePath)
                Redis_pool.delete(redisKey)
                Redis_pool.lpush(redisKey,
                                 "[Start] Ansible Model: {model}  Script:{filePath} {args}".format(
                                     model='copy', filePath=filePath, args=scripts_args))

                ANS = ANSRunner(resource, redisKey)

                ANS.run_model(host_list=sList, module_name='copy',
                              module_args=scripts_args)
                Redis_pool.lpush(redisKey, "[Done] Ansible Done.")
                try:
                    LogFileOps.objects.create(opstype="up",filepath=descpath,server=str(sList),
                                          content=content,
                                          user=str(request.user.username),srcfile=fileobj.name)
                except Exception as e:
                    print(e)
                return JsonResponse({'msg': "操作成功", "code": 200, 'data': []})

            else:
                # print "操作失败，未选择主机或者该分组没有成员"
                return JsonResponse({'msg': "操作失败，未选择主机或者该分组没有成员",
                                     "code": 500, 'data': []})
@login_required()
@permission_verify()
def file_find(request):
    if request.method == "POST":
        form = FileDownForm(request.POST)

        if form.is_valid():
            descpath = form.cleaned_data['filepath']
            inventory = form.cleaned_data['inventory']
            dataList = []
            resource, sList = get_json_inentory(inventory.id, pw="get")
            scripts_args = "path={}".format(descpath)
            ANS = ANSRunner(resource)
            ANS.run_model(host_list=sList, module_name='find',
                          module_args=scripts_args)
            filesData = json.loads(ANS.get_model_result())
            for k, v in filesData.get('success').items():
                for ds in v.get('files'):
                    data = {}
                    # data["id"] = order.id
                    data['host'] = k
                    data['path'] = ds.get('path')
                    data['size'] = round(float(ds.get('size'))/1024,2)
                    data['islnk'] = ds.get('islnk')
                    dataList.append(data)
            return JsonResponse({'msg': "操作成功", "code": 200, 'data': dataList})
        else:
            return JsonResponse({'msg': "操作失败", "code": 500, 'data': []})


@login_required()
@permission_verify()
def file_down(request):
    if request.method == "GET":
        form = FileDownForm()
        uuidkey = uuid.uuid4()
        return render(request, "mfile/file_down.html", locals())


    elif request.method == "POST":

        descpath = request.POST.get('path')
        inventory = request.POST.get('inventory')
        content = request.POST.get('content')
        # print model,args,debug,inventory
        resource, sList = get_json_inentory(inventory, pw="get")

        filePath = os.path.join(os.getcwd(),'upload/myfile/download')
        if not os.path.exists(filePath):
            # print("dir not exists,make it")
            os.makedirs(filePath)

        scripts_args = "src={} dest={} fail_on_missing=yes".format(descpath,filePath,)
        ANS = ANSRunner(resource)
        ANS.run_model(host_list=sList, module_name='fetch',
                      module_args=scripts_args)
        # 日志记录
        try:
            LogFileOps.objects.create(opstype="down",filepath='/upload/myfile/download',
                                      server=str(sList),content=content,
                                      user=str(request.user.username),srcfile=descpath)
        except Exception as e:
            print(e)
        # 文件读取迭代
        def file_iterator(filepath,chunk_size=512):
            with open(filepath,'rb') as f:
                while True:
                    c = f.read(chunk_size)
                    if c:
                        yield c
                    else:
                        break

        result = json.loads(ANS.get_model_result())
        filePath = result.get('success').get(request.POST.get('dest_server')).get('dest')
        if filePath:
            response = StreamingHttpResponse(file_iterator(filePath))
            response = FileResponse(response)
            response['Content-Type'] = 'application/octet-stream'
            response['Content-Disposition'] = 'attachment; filename="{file_name}'.format(
                file_name=os.path.basename(filePath))
            return response

        # return JsonResponse({'msg': "操作成功", "code": 200, 'data': []})

        else:
            # print "操作失败，未选择主机或者该分组没有成员"
            return JsonResponse({'msg': "操作失败，未选择主机或者该分组没有成员",
                                 "code": 500, 'data': []})

@login_required()
@permission_verify()
def file_log(request):
    if request.method == "GET":
        data_list = LogFileOps.objects.all()
        uuidkey = uuid.uuid4()
        return render(request, "mfile/file_log.html", locals())

templates/mfile/file_down.html
{% extends 'base.html' %}


{% block title %}
    <title> ALANCMDB-文件下载 </title>
{% endblock %}


{% block css-js %}
    <!--Ion Icons [ OPTIONAL ]-->
    <link href="/static/css/ionicons.min.css" rel="stylesheet">
    <script src="/static/js/layer/layer.js"></script>
    <!--Nifty Premium Icon [ DEMONSTRATION ]-->
    <link href="/static/css/nifty-demo-icons.min.css" rel="stylesheet">
        <!--DataTables [ OPTIONAL ]-->
    <link href="/static/css/datatables.bootstrap.css" rel="stylesheet">
    <link href="/static/css/datatables.responsive.css" rel="stylesheet">

    <script src="/static/js/jquery.datatables.js"></script>
    <script src="/static/js/datatables.bootstrap.js"></script>
    <script src="/static/js/datatables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="/static/js/tables-datatables.js"></script>

{#<script src="/static/js/ace/ace.js"></script>#}
{#<script src="/static/js/ace/ext-language_tools.js"></script>#}
{#<script src="/static/js/ace/theme-monokai.js"></script>#}



{% endblock %}


{% block page-title %}
    <h1 class="page-header text-overflow">文件下载</h1>
{% endblock %}

{% block content %}
      <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
					<li><a href="/">首页</a></li>
					<li><a href="/mfile/">文件管理</a></li>
					<li class="active">文件下载</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->
    {% if message %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">文件下载</h3>
        </div>
            <div class="panel-body">

                <div class="col-lg-4">
                <legend><i class="fa  fa-paper-plane-o"></i> 文件选项</legend>
                    <form class="form-horizontal" id="filedown_form" role="form"  method="POST">
                    {% csrf_token %}
                        {#            {{ form }}#}
                        {% for item in form %}
                            <div class="form-group">
                                <label class="col-ms-10 control-label"
                                       style="margin-left: 10px;">{{ item.label }}</label>

                                <div class="col-ms-10" style="margin-left: 10px;">
                                    {{ item }}

                                </div>

                                <div class="col-ms-10" style="margin-left: 10px;">
                                    {{ item.errors }}
                                </div>
                            </div>

                        {% endfor %}
                        <input type="hidden" name="uuidkey" value="{{ uuidkey }}">
                        <div class="form-group">
                            <div class="box-footer" style="margin-left: 10px;width: 530px;">
                                <button type="button"  class="btn btn-primary" style="width: 60pt"
                                        id="run_ansible_model" onclick="runAnsibleModel(this)"
                                        >查找
                                </button>
                                <button type="button" style="width: 60pt" onclick="repealFromVaule(this)" class="btn btn-default" >撤销</button>

                            </div>
                        </div>

                    </form>
                </div>
        <div class="col-lg-8">
             <legend><i class="fa  fa-paper-plane-o"></i> 远程文件列表</legend>
                    <div id="result"></div>


        </div>
            </div>
        </div>
    </div>
<div style="visibility:hidden"><a id="scrollToTop"></a></div>


<script>
function runAnsibleModel(obj) {
		var btnObj = $(obj);
		btnObj.attr('disabled',true);
		var form = document.getElementById('filedown_form');
		var post_data = {};
		for (var i = 1; i < form.length; ++i) {
			var name = form[i].name;
			var value = form[i].value;
			var project = name.indexOf("ansible_model");
			if ( project==0 && value.length==0 && name!="ansible_args"){
				window.wxc.xcConfirm("请注意必填项不能为空~", window.wxc.xcConfirm.typeEnum.error);
				btnObj.removeAttr('disabled');
				return false;
			}
		};

		$.ajax({
			url:'/mfile/find/', //请求地址
			type:"POST",  //提交类似
			data:$('#filedown_form').serialize(),  //提交参数
            {#processData: false, //因为data值是FormData对象，不需要对数据做处理#}
            {#data: new FormData($('#ansible_moudel_form')),#}
			success:function(response){
				btnObj.removeAttr('disabled');
				if (response["code"] == "500"){
/* 					clearInterval(interval); */
					btnObj.removeAttr('disabled');
					window.wxc.xcConfirm(response["msg"], window.wxc.xcConfirm.typeEnum.error);
				}
				else{
					var trHtml = '';
					for (var i = 1; i < response["data"].length; ++i) {
						if (response['data'][i]["islnk"] ){
							var button = '<button type="button" class="btn btn-xs btn-default" disabled><abbr title="软连接不支持下载"><i class="fa  fa-cloud-download"></i></button>';
						}else if(response['data'][i]["size"] > 500 ){
							var button = '<button type="button" class="btn btn-xs btn-default" disabled><abbr title="文件过大不支持下载"><i class="fa  fa-cloud-download"></i></button>';
						}else{
							var button = '<button type="button" name="download_button" class="btn btn-xs btn-default" onclick="downLoadOrderFiles(this,\'' + response['data'][i]["path"] + '\',\'' + response['data'][i]["host"] +'\')"><abbr title="下载"><i class="ti-cloud-down"></i></button>';
						}
						trHtml += '<tr><td>'+ i +'</td><td>'+ response['data'][i]["host"] +'</td><td>'+ response['data'][i]["path"] + '</td><td>' + response['data'][i]["size"] + '</td><td>'+ response['data'][i]["islnk"] + '</td><td class="text-center">'+ button +'</td></tr>'
					};
					var vTableHtml = '<div id="result">' +
										'<table id="demo-dt-selection" class="table table-bordered table-striped" >' +

											'<thead>' +
												'<tr>'+
													'<th>id</th>'+
													'<th>主机</th>'+
													'<th>文件路径</th>'+
													'<th>文件大小(KB)</th>'+
													'<th>是否软连接</th>'+
													'<th>下载</th>'+
													'</tr>'+
											'</thead>'+
											'<tbody>' + trHtml +
											'</tbody>'+
										'</table>'+
									'</div>'
					$("#result").html(vTableHtml);
					$('#demo-dt-selection').dataTable( {
					    "order": [[ 3, 'desc' ], [ 3, 'desc' ]]
					});
				}
			},

	    	error:function(response){
	    		btnObj.removeAttr('disabled');
	    		window.wxc.xcConfirm("运行失败", window.wxc.xcConfirm.typeEnum.error);
	    		clearInterval(interval);
	    	}
		})
	}

var downLoadFile = function (options) {
	    var config = $.extend(true, { method: 'post' }, options);
	    var $iframe = $('<iframe id="down-file-iframe"/>');
	    var $form = $("<form target='down-file-iframe' method=" + config.method + " />");
	    $form.attr('action', config.url);
	    for (var key in config.data) {
	        $form.append('<input type="hidden" name="' + key + '" value="' + config.data[key] +  '"/>');
	    }
	    $form.append("{% csrf_token %}");
	    $iframe.append($form);
	    $(document.body).append($iframe);
	    $form[0].submit();
	    $iframe.remove();
	};

	function downLoadOrderFiles(obj,path,host){
		$("button[name='download_button']").attr("disabled",true);
	    var url = '/mfile/down/';
	    {#var data = new FormData(document.getElementById('filedown_form'));#}
        {#    data.append('path', path);#}
        {#    data.append('dest_server', host);#}
        var data = {
				'inventory':document.getElementById('id_inventory').value,
				'content':document.getElementById('id_content').value,
				'path':path,
				'dest_server':host
         };
        downLoadFile({ //调用下载方法
		        url:url,data:data
		        });
        $("button[name='download_button']").attr("disabled",false);
		}
		function repealFromVaule(){
		   document.getElementById("deployRun").reset();}


            {#var form = new FormData(document.getElementById('filedown_form'));#}
            {#form.append('path', path);#}
            {#form.append('dest_server', host);#}
            {#$.ajax({#}
            {#    url: '/mfile/down/', //请求地址#}
            {#    type: "POST",  //提交类似#}
            {#    data: form,#}
            {#    processData: false,#}
            {#    contentType: false,#}
                {#data: $('#fileup_form').serialize(),  //提交参数#}
                {#processData: false, //因为data值是FormData对象，不需要对数据做处理#}
                {#data: new FormData($('#ansible_moudel_form')),#}
            {#    success: function (response) {#}
                    {#btnObj.removeAttr('disabled');#}
            {#        $("button[name='download_button']").attr("disabled",false);#}
            {#        if (response["code"] == "500") {#}
                        {#clearInterval(interval);#}
                        {#btnObj.removeAttr('disabled');#}
            {#            window.wxc.xcConfirm(response["msg"], window.wxc.xcConfirm.typeEnum.error);#}
            {#        }#}
            {##}
            {#    },#}
            {#    error: function (response) {#}
                    {#btnObj.removeAttr('disabled');#}
            {#        $("button[name='download_button']").attr("disabled",false);#}
            {#        window.wxc.xcConfirm("运行失败", window.wxc.xcConfirm.typeEnum.error);#}
            {#        clearInterval(interval);#}
            {#    }#}
            {#})}#}
</script>



{% if errorInfo %}
	window.wxc.xcConfirm("{{errorInfo}}", window.wxc.xcConfirm.typeEnum.error);
{% endif %}

{% endblock %}

templates/mfile/file_log.html
{% extends 'base.html' %}


{% block title %}
<title> 文件操作记录</title>
{% endblock %}


{% block css-js %}

  <!--DataTables [ OPTIONAL ]-->
    <link href="/static/css/datatables.bootstrap.css" rel="stylesheet">
	<link href="/static/css/datatables.responsive.css" rel="stylesheet">

   <script src="/static/js/jquery.datatables.js"></script>
    <script src="/static/js/datatables.bootstrap.js"></script>
	<script src="/static/js/datatables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="/static/js/tables-datatables.js"></script>



{% endblock %}


{% block page-title %}
<h1 class="page-header text-overflow">文件操作记录</h1>
{% endblock %}

{% block content %}

<div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">文件操作记录</h3>
                        </div>


<br>
        <div class="panel-body">

                        <table id="demo-dt-selection" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>序号</th>
              <th>操作类型</th>
              <th>源文件</th>
              <th>目标文件路径</th>
              <th>目标服务器</th>
              <th>操作用户</th>
              <th>操作时间</th>
              <th>备注</th>
            </tr>
            </thead>
            <tbody>

                {% for data in data_list %}
                <tr>
                  <td>{{ forloop.counter }}</td>

                  <td class="text-red text-bold">{{ data.get_opstype_display }}</td>
                  <td>{{ data.srcfile }}</td>
                  <td>{{ data.filepath }}</td>
                  <td>{{ data.server }}</td>
                  <td>{{ data.user}}</td>
                  <td>{{ data.create_time|date:"Y/m/d [H:m:s]" }}</td>
                  <td>{{ data.content }}</td>

                </tr>
                {% empty %}
                  <tr>没有数据！</tr>
                {% endfor %}

            </tbody>

          </table>


					    </div>
					</div>


{% endblock %}

templates/mfile/finder.html
{% extends 'base.html'%}
{% block title %}

{% endblock %}

{% block css-js %}
<link rel="stylesheet" href="/static/css/toastr.css">
<link rel="stylesheet" type="text/css" href="/static/jquery-ui/jquery-ui.css">
<!-- elFinder CSS (REQUIRED) -->
<link rel="stylesheet" type="text/css" href="/static/elfinder/css/elfinder.full.css">

    <script src="/static/jquery-ui/jquery-ui.js"></script>
<!-- elFinder JS (REQUIRED) -->
<script src="/static/elfinder/js/elfinder.full.js"></script>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{%endblock%}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
{#        <div class="col-md-12">#}
          <div class="box box-primary">
            <div class="box-body no-padding">
              <!-- THE CALENDAR -->
              <div id="finder"></div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
{#        </div>#}
    </section>

</div>




<script type="text/javascript" charset="utf-8">
(function($){
        var i18nPath = 'js/i18n',
                start = function(lng) {
                        // disable HTML quicklook plugin
                        elFinder.prototype.commands.quicklook.plugins[1] = null;
                        <!--var high = $('body').find('.sidebar')[0].clientHeight;-->
                        $().ready(function() {
                                //console.log($(".content"));
                                // Documentation for client options:
                                // https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
                                var elfinderInstance = $('#finder').elfinder({
                                        resizable: false,
                                        height: '490px',
                                        url: '/elfinder/yawd-connector/default/files/', // connector URL (REQUIRED)
                                        //url: 'http://hypweb.net/elFinder-nightly/demo/2.1/php-jsb/basic.php',
                                        lang: lng,                    // language (OPTIONAL)
                                        debug: ['error', 'warning', 'event-destroy'],
                                        dragUploadAllow: true,
                                        soundPath: "/static/elfinder/sounds/rm.wav"
                                }).elfinder('instance');

                                // set document.title dynamically etc.
                                var title = document.title;
                                elfinderInstance.bind('open', function(event) {
                                        var data = event.data || null;
                                        var path = '';
                                        
                                        if (data && data.cwd) {
                                                path = elfinderInstance.path(data.cwd.hash) || null;
                                        }
                                        document.title =  path? path + ':' + title : title;
                                });

                                // fit to window.height on window.resize
                                <!--var resizeTimer = null;-->
                                <!--$(window).resize(function() {-->
                                        <!--resizeTimer && clearTimeout(resizeTimer);-->
                                        <!--resizeTimer = setTimeout(function() {-->
                                                <!--var h = parseInt(high);-->
                                                <!--if (h != parseInt($('#finder').height())) {-->
                                                        <!--elfinderInstance.resize('1000px', high);-->
                                                <!--}-->
                                        <!--}, 0);-->
                                <!--});-->
                        });
                },
                loct = window.location.search,
                full_lng, locm, lng;
        
        // detect language
        if (loct && (locm = loct.match(/lang=([a-zA-Z_-]+)/))) {
                full_lng = locm[1];
        } else {
                full_lng = (navigator.browserLanguage || navigator.language || navigator.userLanguage);
        }
        lng = full_lng.substr(0,2);
        if (lng == 'ja') lng = 'jp';
        else if (lng == 'pt') lng = 'pt_BR';
        else if (lng == 'zh') lng = (full_lng.substr(0,5) == 'zh-tw')? 'zh_TW' : 'zh_CN';

        if (lng != 'en') {
                $.ajax({
                        url : '',
                        cache : true,
                        dataType : 'script'
                })
                .done(function() {
                        start(lng);
                })
                .fail(function() {
                        start('en');
                });
        } else {
                start(lng);
        }
})(jQuery);
</script>

{% endblock %}