SimpleOps/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import accounts.urls
from . import views
import accounts.user
import cmdb.urls
import chat.urls
import setup_jobs.urls
import deploy.urls
import api.urls
import delivery.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^login/',accounts.user.login,name='login'),
    url(r'^user/', include('accounts.urls')),
    url(r'^logout/', accounts.user.logout, name='logout'),
    url(r'^cmdb/',include('cmdb.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^setup_jobs/',include('setup_jobs.urls')),
    url(r'^deploy/',include('deploy.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^mfile/', include('mfile.urls')),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^delivery/', include('delivery.urls')),
    url(r'^config/$', views.config,name='config'),
    # url(r'^websocket/(?P<userid>[0-9]+)$',views.websocket_tst,name='websocket'),
]
handler400 = "SimpleOps.views.bad_request"
handler404 = "SimpleOps.views.page_not_found"
handler403 = "SimpleOps.views.page_not_permission"
handler500 = "SimpleOps.views.internl_error"

api/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    url(r'^assets/$', views.assets_list),
    url(r'^project/$', views.project_list),
    url(r'^project/(?P<id>[0-9]+)/$', views.project_detail),
    url(r'^inventory/(?P<id>[0-9]+)/$', views.inventory_detail),
    url(r'^service/$', views.service_list),
    url(r'^service/(?P<id>[0-9]+)/$', views.service_detail),
    url(r'^assets/(?P<id>[0-9]+)/$', views.assets_detail),

]

urlpatterns = format_suffix_patterns(urlpatterns)

cmdb/urls.py
from django.conf.urls import url

import views

app_name = "cmdb"
urlpatterns = [
    url(r'^report/', views.report, name='report'),
    url(r'^assets_info/$', views.assets_info, name='assets_info'),
    url(r'^project/', views.project, name='project'),
    url(r'^new_asset_permission/$', views.new_asset_permission, name='new_asset_permission'),
    url(r'^new_asset_del/(?P<asset_id>[0-9]+)/$', views.new_asset_del, name='new_asset_del'),
    url(r'^new_asset_allow/(?P<asset_id>[0-9]+)/$', views.new_asset_allow, name='new_asset_allow'),
    url(r'^business_unit/$', views.business_unit, name='business_unit'),
    url(r'^business_add/$', views.business_add, name='business_add'),
    url(r'^business_edit/(?P<bus_id>[0-9]+)/$', views.business_edit, name='business_edit'),
    url(r'^business_del/(?P<bus_id>[0-9]+)/$', views.business_del, name='business_del'),
    url(r'^project_list/$', views.project_list, name='project_list'),
    url(r'^project_add/$', views.project_add, name='project_add'),
    url(r'^project_edit/(?P<bus_id>[0-9]+)/$', views.project_edit, name='project_edit'),
    url(r'^project_del/(?P<bus_id>[0-9]+)/$', views.project_del, name='project_del'),
    url(r'^detail/(?P<asset_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^asset_server_query/$', views.assets_server_query, name='assets_server_query'),
    url(r'^asset_edit/(?P<asset_id>[0-9]+)/$', views.asset_edit, name='asset_edit'),
    url(r'^asset_del/(?P<asset_id>[0-9]+)/$', views.asset_del, name='asset_del'),
    url(r'^asset_add/', views.asset_add, name='asset_add'),
    url(r'^asset_batch_import/', views.asset_batch_import, name='asset_batch_import'),
]

mfile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from mfile.views import finder,file_down,file_log,file_up,file_find
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^up/', file_up),
    url(r'^down/', file_down),
    url(r'^find/', file_find),
    url(r'^log/', file_log),
    url(r'^$',finder.as_view(),name='mfile'),
    url(r'^elfinder/',include('elfinder.urls')),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
    ]

cmdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from accounts.models import User_info


# Create your models here.
class Assets(models.Model):
    asset_type_choice = (
        ('server', '物理机'),
        ('vmserver', '虚拟机'),
        ('docker', '容器'),
        ('netdevice', '网络设备'),
        ('storagedevice', '存储设备'),
        ('others', '其他'),
    )
    asset_status_choice = (
        ('1', '在线'),
        ('2', '下线'),
        ('3', '故障'),
        ('4', '备用'),
        ('5', '未知'),
    )
    asset_type = models.CharField(choices=asset_type_choice, max_length=60, default='vmserver', verbose_name='资产类型')
    name = models.CharField(max_length=100, verbose_name='资产名称', unique=True)
    sn = models.CharField(max_length=100, verbose_name='资产序号', unique=True)
    status = models.CharField(choices=asset_status_choice, max_length=10, default='1', verbose_name='资产状态')
    business_unit = models.ForeignKey('BusinessUnit', null=True, blank=True,
                                      related_name='project_assets',verbose_name='所属业务线')

    service = models.SmallIntegerField(blank=True, null=True, verbose_name='所属业务')
    group = models.SmallIntegerField(blank=True, null=True, verbose_name='分组')
    asset_model = models.CharField(max_length=100, blank=True, null=True, verbose_name='资产型号')
    manufacturer = models.ForeignKey('Manufacturer', blank=True, null=True,
                                     related_name='manufacturer_assets',verbose_name='供货商')
    site = models.CharField(blank=True, null=True, max_length=100, verbose_name='位置')
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    manager = models.CharField(blank=True, null=True, max_length=100, verbose_name='管理人员')

    buy_time = models.DateField(blank=True, null=True, verbose_name='购买时间')
    expire_date = models.DateField(null=True, blank=True, verbose_name='过保时间')
    approved_by = models.ForeignKey(User_info, verbose_name='批准人', null=True, blank=True, related_name='approved_by')
    memo = models.TextField(null=True, blank=True, verbose_name='备注')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='创建日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __unicode__(self):
        return "{0}|{1}".format(self.name,self.manage_ip)

    class Meta:
        verbose_name = '总资产表'
        verbose_name_plural = '总资产表'
        ordering = ['-c_time']


class Server_asset(models.Model):
    created_by_choice = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )
    asset = models.OneToOneField('Assets')
    created_by = models.CharField(choices=created_by_choice, max_length=32, default='auto', verbose_name="添加方式")
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server',
                                  blank=True, null=True, verbose_name="宿主机")
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='服务器型号')
    raid_type = models.CharField(max_length=512, blank=True, null=True, verbose_name='Raid类型')

    ip = models.CharField(max_length=100, unique=True, blank=True, null=True, verbose_name="IP")
    hostname = models.CharField(max_length=100, blank=True, null=True, verbose_name="主机名")
    username = models.CharField(max_length=100, blank=True, null=True, verbose_name="用户名")
    passwd = models.CharField(max_length=100, blank=True, null=True, verbose_name="密码")
    sudo_passwd = models.CharField(max_length=100, blank=True, null=True, verbose_name="sudo密码")
    keyfile = models.CharField(max_length=100, blank=True, null=True,
                               verbose_name="密钥路径")  # FileField(upload_to = './upload/key/',blank=True,null=True,verbose_name='密钥文件')
    port = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True, verbose_name="端口")
    line = models.CharField(max_length=100, blank=True, null=True, verbose_name='线路')
    # cpu_model = models.CharField(max_length=100, blank=True, null=True, verbose_name='cpu型号')
    # cpu_number = models.SmallIntegerField(blank=True, null=True, verbose_name='cpu个数')
    # cpu_core = models.SmallIntegerField(blank=True, null=True, verbose_name='cpu核数')
    disk_total = models.CharField(max_length=100, blank=True, null=True, verbose_name='磁盘容量')
    ram_total = models.CharField(max_length=100, blank=True, null=True, verbose_name='内存容量')
    swap = models.CharField(max_length=100, blank=True, null=True, verbose_name='swap')
    raid = models.SmallIntegerField(blank=True, null=True, verbose_name='raid方式')

    os_type = models.CharField(max_length=64, blank=True, null=True, verbose_name="操作系统类型")
    os_distribution = models.CharField(verbose_name='发行版本', max_length=64, blank=True, null=True)
    os_release = models.CharField(verbose_name='操作系统版本', max_length=64, blank=True, null=True)

    def __unicode__(self):
        # return '%s--%s <sn:%s>' % (self.asset.name, self.asset.asset_model, self.asset.sn)
        # return self.asset.name
        return "{0}|{1}".format(self.asset.name, self.asset.manage_ip)
    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"


class Network_asset(models.Model):
    assets = models.OneToOneField('Assets')
    bandwidth = models.CharField(max_length=100, blank=True, null=True, verbose_name='背板带宽')
    ip = models.CharField(unique=True, max_length=100, blank=True, null=True, verbose_name='管理ip')
    username = models.CharField(max_length=100, blank=True, null=True)
    passwd = models.CharField(max_length=100, blank=True, null=True)
    sudo_passwd = models.CharField(max_length=100, blank=True, null=True)
    port = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True)
    port_number = models.SmallIntegerField(blank=True, null=True, verbose_name='端口个数')
    firmware = models.CharField(max_length=100, blank=True, null=True, verbose_name='固件版本')
    cpu = models.CharField(max_length=100, blank=True, null=True, verbose_name='cpu型号')
    stone = models.CharField(max_length=100, blank=True, null=True, verbose_name='内存大小')
    configure_detail = models.TextField(max_length=100, blank=True, null=True, verbose_name='配置说明')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.assets.name

    class Meta:
        verbose_name = '网络资产表'
        verbose_name_plural = '网络资产表'


class NIC(models.Model):
    """网卡组件"""

    asset = models.ForeignKey('Assets')  # 注意要用外键
    name = models.CharField('网卡名称', max_length=64, blank=True, null=True)
    model = models.CharField('网卡型号', max_length=128)
    mac = models.CharField('MAC地址', max_length=64)  # 虚拟机有可能会出现同样的mac地址
    ip_address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    net_mask = models.CharField('掩码', max_length=64, blank=True, null=True)
    bonding = models.CharField('绑定地址', max_length=64, blank=True, null=True)
    active = models.BooleanField('是否在线', default=True)

    def __unicode__(self):
        return '%s:  %s:  %s' % (self.asset.name, self.model, self.mac)

    class Meta:
        verbose_name = '网卡'
        verbose_name_plural = "网卡"
        unique_together = ('asset', 'model', 'mac')


class CPU(models.Model):
    """CPU组件"""

    asset = models.OneToOneField('Assets')
    cpu_model = models.CharField('CPU型号', max_length=128, blank=True, null=True)
    cpu_number = models.PositiveSmallIntegerField('物理CPU个数', default=1)
    cpu_core = models.PositiveSmallIntegerField('CPU核数', default=1)

    def __unicode__(self):
        # return self.asset.name + ":   " + self.cpu_model
        return self.asset.name
    class Meta:
        verbose_name = 'CPU'
        verbose_name_plural = "CPU"

class Ram_asset(models.Model):
    """内存组件"""

    asset = models.ForeignKey('Assets')  # 只能通过外键关联Asset。否则不能同时关联服务器、网络设备等等。
    sn = models.CharField('SN号', max_length=128, blank=True, null=True)
    model = models.CharField('内存型号', max_length=128, blank=True, null=True)
    manufacturer = models.CharField('内存制造商', max_length=128, blank=True, null=True)
    slot = models.CharField('插槽', max_length=64)
    capacity = models.IntegerField('内存大小(GB)', blank=True, null=True)
    device_status = models.CharField('内存状态', max_length=100, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.asset.name

    class Meta:
        verbose_name = '内存'
        verbose_name_plural = "内存"
        unique_together = ('asset', 'slot')  # 同一资产下的内存，根据插槽的不同，必须唯一


class Disk_asset(models.Model):
    """存储设备"""

    disk_interface_type_choice = (
        ('SATA', 'SATA'),
        ('SAS', 'SAS'),
        ('SCSI', 'SCSI'),
        ('SSD', 'SSD'),
        ('unknown', 'unknown'),
    )

    asset = models.ForeignKey('Assets')
    sn = models.CharField('硬盘SN号', max_length=128)
    slot = models.CharField('所在插槽位', max_length=64, blank=True, null=True)
    model = models.CharField('磁盘型号', max_length=128, blank=True, null=True)
    manufacturer = models.CharField('磁盘制造商', max_length=128, blank=True, null=True)
    capacity = models.FloatField('磁盘容量(GB)', blank=True, null=True)
    interface_type = models.CharField('接口类型', max_length=16, choices=disk_interface_type_choice, default='unknown')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.asset.name

    class Meta:
        verbose_name = '硬盘'
        verbose_name_plural = "硬盘"
        unique_together = ('asset', 'sn')


class SecurityDevice(models.Model):
    """安全设备"""
    sub_asset_type_choice = (
        (0, '防火墙'),
        (1, '入侵检测设备'),
        (2, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Assets')

templates/cmdb/assets.html
{% extends 'base.html' %}


{% block title %}
<title> ALANCMDB-资产总表 </title>
{% endblock %}


{% block css-js %}

  <!--DataTables [ OPTIONAL ]-->
    <link href="/static/css/datatables.bootstrap.css" rel="stylesheet">
	<link href="/static/css/datatables.responsive.css" rel="stylesheet">

   <script src="/static/js/jquery.datatables.js"></script>
    <script src="/static/js/datatables.bootstrap.js"></script>
	<script src="/static/js/datatables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="/static/js/tables-datatables.js"></script>



{% endblock %}


{% block page-title %}
<h1 class="page-header text-overflow">Asset Manger</h1>
{% endblock %}

{% block content %}

<div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">资产总表</h3>
                        </div>

                            <li class="pull-left btn">
                            <a href="{% url 'cmdb:asset_add' %}" class="btn btn-success btn-bock" >
                                <b>新增资产</b>
                            </a>
                            </li>
                <li class="pull-right btn">
                                 <form  method="post" enctype="multipart/form-data" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"  id="assets_form">
                            {% csrf_token %}
                    <li class="btn btn-success btn-file">
					                        <input type="file" name="batch_import">
                                    <b>上传excel文件</b>
                                </li>
                                     <li class="btn ">
                                     <button id="batch_import" class="btn btn-success">
                                         <b>批量导入</b>
                                     </button>
                                     </li>
</form>
</li>
<br>
<br>
        <div class="panel-body">

                        <table id="demo-dt-selection" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>序号</th>
              <th>资产类型</th>
              <th>资产名称</th>
{#              <th>SN</th>#}
              <th>管理IP</th>
              <th>业务线</th>
              <th>状态</th>
              <th>机房</th>
              <th>更新日期</th>
              <th>标签</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

                {% for asset in asset_data %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  {% if asset.asset_type == 'server' or asset.asset_type == 'vmserver' or asset.asset_type == 'docker' %}
                      <td class="text-green text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "netdevice" %}
                      <td class="text-yellow text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "storagedevice" %}
                      <td class="text-blue text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "others" %}
                      <td class="text-red text-bold">{{ asset.get_asset_type_display }}</td>

                  {% endif %}
                    {% if asset.asset_type == 'server' %}
                        <td><a href="{% url 'cmdb:detail' asset.id %}">{{ asset.name }}</a></td>
                    {% else %}
                        <td>{{ asset.name }}</td>
                    {% endif %}
{#                  <td>{{ asset.sn }}</td>#}
                  <td>{{ asset.manage_ip }}</td>
                  <td>{{ asset.business_unit|default_if_none:"-" }}</td>
                    {% if asset.status == "1" %}
                      <td><label class="label label-success">{{ asset.get_status_display }}</label></td>
                    {% elif asset.status == "2" %}
                      <td><label class="label label-warning">{{ asset.get_status_display }}</label></td>
                    {% elif asset.status == "3" %}
                      <td><label class="label label-default">{{ asset.get_status_display }}</label></td>
                    {% elif asset.status == "4" %}
                      <td><label class="label label-danger">{{ asset.get_status_display }}</label></td>
                    {% elif asset.status == "5" %}
                      <td><label class="label label-info">{{ asset.get_status_display }}</label></td>
                    {% endif %}
                  <td>{{ asset.site|default:"-" }}</td>
                  <td>{{ asset.m_time|date:"Y/m/d [H:m:s]" }}</td>
                  <td>
                      {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                      {% empty %}
                          -
                      {% endfor %}
                  </td>
                <td class="text-center" data-editable='false'>
                                        <a href="{% url 'cmdb:asset_edit' asset.id %}" class="btn btn-sm btn-info">编辑</a>
                                        <a href="{% url 'cmdb:asset_del' asset.id %}" class="btn btn-sm btn-danger user_del"  onclick="return confirm('确认删除？')">删除</a>
                                    </td>
                </tr>
                {% empty %}
                  <tr>没有数据！</tr>
                {% endfor %}

            </tbody>
            <tfoot>
            <tr>
            <th>序号</th>
              <th>资产类型</th>
              <th>资产名称</th>
{#              <th>SN</th>#}
              <th>管理IP</th>
              <th>业务线</th>
              <th>状态</th>
              <th>机房</th>
              <th>更新日期</th>
              <th>标签</th>
                <th>操作</th>
            </tr>
            </tfoot>
          </table>


					    </div>
					</div>

{#<script src="/static/js/csrf.js"></script>#}
<script>
    $('#batch_import').click(function(){
        $.ajax({
            {#dataType: "JSON",#}
            url: '/cmdb/asset_batch_import/', //请求地址
            type: "POST",  //提交类似
            cache: false, //上传文件不需要缓存。
            processData: false, //因为data值是FormData对象，不需要对数据做处理
            contentType: false,  //因为是由<form>表单构造的FormData对象，且已经声明了属性enctype="multipart/form-data"，所以这里设置为false
            data: new FormData($('#assets_form')[0])

        }).done(function (res) {
        alert("新增资产已成功添加到待审区！");
    }).fail(function (res) {
        alert("新增资产失败，请检查数据！");
    })
    });

</script>

{% endblock %}

templates/cmdb/business_info.html
{% extends 'base.html' %}


{% block title %}
    <title> ALANCMDB-业务线管理 </title>
{% endblock %}


{% block css-js %}




{% endblock %}


{% block page-title %}
    <h1 class="page-header text-overflow">Business Manger</h1>
{% endblock %}

{% block content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">业务线管理</h3>


            <li class="pull-left btn">
                <a href="{% url 'cmdb:business_add' %}" class="btn btn-success btn-bock">
                    <b>新增业务线</b>
                </a>
            </li>
        </div>
        <div class="panel-body">

            <table id="assets_table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>业务线名称</th>
                    <th>上级业务线</th>
                    <th>业务线说明</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>

                {% for d in bus_data %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ d.name }}</td>
                        <td>{{ d.parent_unit|default_if_none:"-" }}</td>
                        <td>{{ d.memo }}</td>
                        <td>{{ d.manager }}</td>
                        <td class="text-center" data-editable='false'>
                            {% if d.id %}
                            <a href="{% url "cmdb:business_edit" d.id %}" class="btn btn-sm btn-info">编辑</a>
                            <a href="{% url "cmdb:business_del" d.id %}" class="btn btn-sm btn-danger user_del"
                               onclick="return confirm('确认删除？')">删除</a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>没有数据！</tr>
                {% endfor %}
                </tbody>
            </table>


        </div>
    </div>




{% endblock %}

templates/cmdb/new_asset.html
{% extends 'base.html' %}


{% block title %}
    <title> ALANCMDB-待审核资产表 </title>
{% endblock %}


{% block css-js %}

  <!--DataTables [ OPTIONAL ]-->
    <link href="/static/css/datatables.bootstrap.css" rel="stylesheet">
	<link href="/static/css/datatables.responsive.css" rel="stylesheet">

   <script src="/static/js/jquery.datatables.js"></script>
    <script src="/static/js/datatables.bootstrap.js"></script>
	<script src="/static/js/datatables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="/static/js/tables-datatables.js"></script>



{% endblock %}


{% block page-title %}
    <h1 class="page-header text-overflow">Asset Manger</h1>
{% endblock %}

{% block content %}
     {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

<div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">待审批资产</h3>
					    </div>

{#                        <div class="col-sm-2" style="padding-left: 0">#}
                            <a href="{% url 'cmdb:asset_add' %}" style="margin: 20px">
                                <li class="btn btn-success"><b>新增资产</b></li>
                            </a>
 <li class="pull-right btn">
                                 <form  method="post" enctype="multipart/form-data" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"  id="assets_form">
                            {% csrf_token %}
                    <li class="btn btn-success btn-file">
					                        <input type="file" name="batch_import">
                                    <b>上传excel文件</b>
                                </li>
                                     <li class="btn ">
                                     <button id="batch_import" class="btn btn-success">
                                         <b>批量导入</b>
                                     </button>
                                     </li>
</form>
</li>
<br>
<br>
{#                        </div>#}
        <div class="panel-body">

                        <table id="demo-dt-selection" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>序号</th>
              <th>资产类型</th>
              <th>资产名称</th>
              <th>SN</th>
              <th>位置</th>
                <th>创建时间</th>
              <th>更新时间</th>

                <th>操作</th>
            </tr>
            </thead>
            <tbody>

                {% for asset in asset_data %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  {% if asset.asset_type == 'server' or asset.asset_type == 'vmserver' or asset.asset_type == 'docker' %}
                      <td class="text-green text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "netdevice" %}
                      <td class="text-yellow text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "storagedevice" %}
                      <td class="text-blue text-bold">{{ asset.get_asset_type_display }}</td>

                  {% elif asset.asset_type == "others" %}
                      <td class="text-red text-bold">{{ asset.get_asset_type_display }}</td>

                  {% endif %}
                    {% if asset.asset_type == 'server' %}
                        <td><a href="{% url 'cmdb:detail' asset.id %}">{{ asset.name }}</a></td>
                    {% else %}
                        <td>{{ asset.name }}</td>
                    {% endif %}
                  <td>{{ asset.sn }}</td>

                  <td>{{ asset.site|default:"-" }}</td>
                <td>{{ asset.c_time|date:"Y/m/d [H:m:s]" }}</td>
                  <td>{{ asset.m_time|date:"Y/m/d [H:m:s]" }}</td>

                <td class="text-center" data-editable='false'>
                    {% if asset.id %}
                                        <a href="{% url 'cmdb:new_asset_allow' asset.id %}" class="btn btn-sm btn-info">确认新增</a>
                                        <a href="{% url 'cmdb:new_asset_del' asset.id %}" class="btn btn-sm btn-danger user_del"  onclick="return confirm('确认删除？')">删除资产</a>
                    {% endif %}
                                    </td>
                </tr>
                {% empty %}
                  <tr>没有数据！</tr>
                {% endfor %}

            </tbody>
          </table>


					    </div>
					</div>

    <script>
$('#batch_import').click(function(){
        $.ajax({
            {#dataType: "JSON",#}
            url: '/cmdb/asset_batch_import/', //请求地址
            type: "POST",  //提交类似
            cache: false, //上传文件不需要缓存。
            processData: false, //因为data值是FormData对象，不需要对数据做处理
            contentType: false,  //因为是由<form>表单构造的FormData对象，且已经声明了属性enctype="multipart/form-data"，所以这里设置为false
            data: new FormData($('#assets_form')[0]),
            success: function (response) {
                {#document.getElementById("ajax-log").innerHTML=response['data'];#}
                alert("新增资产已成功添加到待审区！");
            },
            error: function () {
                alert("新增资产失败，请检查数据！");//获取抛出的错误信息
                },
        })})
</script>

{% endblock %}